# Generated by Django 5.2.1 on 2026-03-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("business_admin", "Business Administrator"),
                    ("manager", "Manager / Supervisor"),
                    ("salesperson", "Salesperson"),
                    ("erp_operator", "ERP Operator"),
                    ("basic_user", "Basic User"),
                ],
                default="basic_user",
                max_length=20,
            ),
        ),
    ]
