# Generated by Django 5.2.1 on 2026-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("user_created", "User Created"),
                    ("user_updated", "User Updated"),
                    ("user_deactivated", "User Deactivated"),
                    ("role_changed", "Role Changed"),
                    ("customer_updated", "Customer Updated"),
                    ("customer_deactivated", "Customer Deactivated"),
                    ("contact_updated", "Contact Updated"),
                    ("lead_updated", "Lead Updated"),
                ],
                max_length=50,
            ),
        ),
    ]
