# Generated by Django 5.2.1 on 2026-03-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
    ]
