# Generated by Django 5.2.1 on 2026-03-26 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("customers", "0002_alter_customer_options"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers_contacts",
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants_contact",
                to="tenants.tenant",
            ),
        ),
    ]
