# Generated by Django 5.2.1 on 2026-03-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_customer_alter_contact_tenant"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("email", "tenant")},
        ),
    ]
